inherits = "base.toml"

[pacman]
[pacman.packages]
    apricity = [
        "python",
        "xz"
    ]

[vim]
plugin_manager = "pathogen"
[vim.plugins]
    apricity = [
        "https://github.com/chriskempson/base16-vim.git/",
        "https://github.com/scrooloose/syntastic.git/",
        "https://github.com/bling/vim-airline/",
        "https://github.com/hynek/vim-python-pep8-indent.git/",
        "https://github.com/mhinz/vim-signify/"
    ]
