[pacman]
[pacman.packages]
    apricity = [
        "tar"
    ]
    base = [
        "git"
    ]

[systemd]
[systemd.services]
    apricity = [
        "org.cups.cupsd",
        "smbd",
        "nmbd",
        "graphical.target",
        "gdm"
    ]
